name: Pipeline Cypress web

on: 
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v4

      - name: Cypress run testes
        uses: cypress-io/github-action@v7
        with:
          record: true
        env: 
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
