# Nome da pipeline.
name: Pipeline Cypress web

# Em que momento que a pipeline será executada.
on: 
  pull_request:
    branches: [master]

jobs:
  # O que vai ser executado na pipeline.
  cypress-run:
    # Em qual máquina que a pipeline será executada
    runs-on: ubuntu-24.04

    # Passos que serão executados na pipeline
    steps:
      # Clone do projeto (Versão estável atualizada)
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v4

      # Instalação das dependências e execução dos testes do Cypress
      - name: Cypress run testes
        uses: cypress-io/github-action@v7
        with:
          working-directory: projetocypress-web
          record: true
        env: 
          # Variável de ambiente configurada nos Secrets do GitHub
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
