# Nome da pipeline
name: Pipeline de agendamento Cypress web

# Em que momento será executada, nesse caso quando haver um pull request na branch master
on:
  schedule:
    - cron: '0 14 * * 1-3'

jobs:
  cypress-run:
    # Maquina que será utilizada para executar a pipeline
    runs-on: ubuntu-24.04

    # Passos para executar os testes da pipeline
    steps:
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v4

      # Instlação dos dependeências do cypress que é executado no terminal        
      - name: Instalar dependências do projeto
        run: npm install

      # Execução e configuração do projeto
      - name: Cypress run testes
        uses: cypress-io/github-action@v7
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # Upload do relatório do mocha
      - name: upload relatório
        uses: actions/upload-artifact@v7
        with:
          name: Relatório Mocha
          path: cypress/reports
          if-no-files-found: error